variable "region" {
  description = "specify region name"
  type        = string
  default     = "us-east-1"
}

variable "iam_role_name" {
  description = "Friendly name of the role. If omitted, Terraform will assign a random, unique name"
  type        = string
  default     = ""
}

variable "iam_role_permissions_boundary" {
  description = "ARN of the policy that is used to set the permissions boundary for the role."
  type        = string
  default     = ""
}

variable "iam_role_description" {
  description = "Description of the role."
  type        = string
  default     = ""
}

variable "force_detach_policies" {
  description = "Whether to force detaching any policies the role has before destroying it. Defaults to false. But i prefer the value true"
  type        = string
  default     = "true"
}

variable "assume_role_policy" {
  description = "Policy that grants an entity permission to assume the role."
  type        = string
}

variable "managed_policy_arns" {
  description = "Set of exclusive IAM managed policy ARNs to attach to the IAM role. If this attribute is not configured, Terraform will ignore policy attachments to this resource. When configured, Terraform will align the role's managed policy attachments with this set by attaching or detaching managed policies. Configuring an empty set (i.e., managed_policy_arns = []) will cause Terraform to remove all managed policy attachments."
  type        = list(string)
  default     = []
}

variable "inline_policy" {
  description = "iamrole_inline_policy creation "
  type        = list(any)
  default     = []
}

variable "max_session_duration" {
  description = "Maximum session duration (in seconds) that you want to set for the specified role. If you do not specify a value for this setting, the default maximum of one hour is applied. This setting can have a value from 1 hour to 12 hours."
  type        = number
  default     = "3600"
}

variable "tags" {
  description = "Key-value mapping of tags for the IAM role. If configured with a provider default_tags configuration block present, tags with matching keys will overwrite those defined at the provider-level."
  type        = map(string)
  default     = {}
}

variable "create_iam_service_linked_role" {
  description = "Do you want to create iam service linked role ? default is false"
  type        = bool
  default     = false
}

variable "aws_service_name" {
  description = "The AWS service to which this role is attached. You use a string similar to a URL but without the http:// in front. For example: elasticbeanstalk.amazonaws.com"
  type        = string
  default     = ""
}

variable "create_iam_saml_provider" {
  description = "Want to create smal provider ? default is false"
  type        = bool
  default     = false
}

variable "saml_provider_name" {
  description = "The name of the provider to create."
  type        = string
  default     = ""
}

variable "saml_metadata_document" {
  description = "An XML document generated by an identity provider that supports SAML 2.0."
  type        = string
  default     = ""
}

variable "create_iam_oidc" {
  description = "Do you want to create OIDC provider ? default is false"
  type        = bool
  default     = false
}

variable "oidc_url" {
  description = "The URL of the identity provider. Corresponds to the iss claim."
  type        = string
  default     = ""
}

variable "oidc_client_id_list" {
  description = "A list of client IDs (also known as audiences). When a mobile or web app registers with an OpenID Connect provider, they establish a value that identifies the application. (This is the value that's sent as the client_id parameter on OAuth requests.)"
  type        = list(string)
  default     = []
}

variable "oidc_thumbprint_list" {
  description = "A list of server certificate thumbprints for the OpenID Connect (OIDC) identity provider's server certificate(s)."
  type        = list(string)
  default     = []
}